#!/bin/bash
clear

# -----------------------------------------------------------------------------

# Enable maintenance mode
php bin/magento maintenance:enable

# Cleanup
rm -rf ./generated/* ./pub/static/adminhtml/* ./var/cache/* ./var/page_cache/* ./var/view_preprocessed/*
rm -f ./pub/static/deployed_version.txt

# Flush cache
php bin/magento cache:flush

# Run setup scripts
php bin/magento setup:upgrade

# Deploy static files
php bin/magento setup:static-content:deploy en_US --area="adminhtml" --no-html-minify -f

# Disable maintenance mode
php bin/magento maintenance:disable
