#!/bin/bash
clear

# -----------------------------------------------------------------------------

# Enable maintenance mode
php bin/magento maintenance:enable

# Cleanup
rm -rf ./generated/* ./pub/static/adminhtml/* ./pub/static/frontend/* ./var/cache/* ./var/page_cache/* ./var/view_preprocessed/*
rm -f ./pub/static/deployed_version.txt

# Flush cache
php bin/magento cache:flush

# Update required components
composer update

# Run setup scripts
php bin/magento setup:upgrade

# Reindex
php bin/magento indexer:reindex

# Resize images
php bin/magento catalog:images:resize

# Deploy static view files
php bin/magento setup:static-content:deploy en_US --no-html-minify -f

# Disable maintenance mode
php bin/magento maintenance:disable
