#!/bin/bash
clear

# -----------------------------------------------------------------------------

# Enable maintenance mode
php bin/magento maintenance:enable

# Cleanup
rm -rf ./generated/* ./var/di/*

# Flush cache
php bin/magento cache:flush

# Compile code
php bin/magento setup:di:compile

# Disable maintenance mode
php bin/magento maintenance:disable
