#!/bin/bash
clear

# -----------------------------------------------------------------------------

# Enable maintenance mode
php bin/magento maintenance:enable

# Cleanup
rm -rf ./generated/* ./pub/static/adminhtml/* ./pub/static/frontend/* ./var/cache/* ./var/page_cache/* ./var/view_preprocessed/*
rm -rf ./pub/media/catalog/product/cache/*
rm -f ./pub/static/deployed_version.txt

# Update required components
composer update

# Flush cache
php bin/magento cache:flush

# Run setup scripts
php bin/magento setup:upgrade

# Reindex
php bin/magento indexer:reindex

# Deploy static view files
php bin/magento setup:static-content:deploy en_US --no-html-minify -f

# Disable maintenance mode
php bin/magento maintenance:disable
