#!/bin/bash
clear

# -----------------------------------------------------------------------------

input_deploy="n"

for i in "$@"
do
    case $i in
        -s|--static-content-deploy)
            input_deploy=y
        ;;
    esac
done

if [ "$input_deploy" == "n" ]
then
    read -r -t 3 -p "Deploy static view files? [Y/n] " input_deploy
    echo
fi

# -----------------------------------------------------------------------------

# Enable maintenance mode
php bin/magento maintenance:enable

# Cleanup
rm -rf ./generated/* ./pub/static/adminhtml/* ./pub/static/frontend/* ./var/cache/* ./var/page_cache/* ./var/view_preprocessed/*
rm -f ./pub/static/deployed_version.txt

# Flush cache
php bin/magento cache:flush

# Update required components
composer update

# Run setup scripts
php bin/magento setup:upgrade

# Reindex
php bin/magento indexer:reindex

# Resize images
# php bin/magento catalog:images:resize

case "$input_deploy" in
    [yY])
        # Deploy static view files
        php bin/magento setup:static-content:deploy --no-html-minify -f
    ;;
    [nN])
        # Skip
    ;;
    *)
        # Help
    ;;
esac

# Disable maintenance mode
php bin/magento maintenance:disable
