#!/bin/bash
clear

# -----------------------------------------------------------------------------

THEME=$1
LOCALE=$2

# -----------------------------------------------------------------------------

rm -rf "pub/static/frontend/$THEME/$LOCALE" \
       "var/cache" \
       "var/page_cache" \
       "var/view_preprocessed/less/frontend/$THEME/$LOCALE" \
       "var/view_preprocessed/pub/static/frontend/$THEME/$LOCALE" \
       "var/view_preprocessed/source/frontend/$THEME/$LOCALE"

# -----------------------------------------------------------------------------

php bin/magento setup:static-content:deploy $LOCALE --theme="$THEME" --no-html-minify -f
